### ISSUE TITLE
NameError: name 'eventlog_touched' is not defined

### ISSUE THREAD

**Issue by cipig** [qtumproject/qtum-electrumx-server#10]
after i updated qtumd to `"version": 220100,` i am seeing this errors in the electrumx logs:
```
Jun 07 16:49:31 electrum1 electrumxqtum_server[1531599]: ERROR:ElectrumX:[6161] unexpected exception notifying client
Jun 07 16:49:31 electrum1 electrumxqtum_server[1531599]: Traceback (most recent call last):
Jun 07 16:49:31 electrum1 electrumxqtum_server[1531599]:   File "/usr/local/lib/python3.9/dist-packages/electrumxqtum/server/session.py", line 1086, in notify
Jun 07 16:49:31 electrum1 electrumxqtum_server[1531599]:     await self._notify_inner(touched, height_changed)
Jun 07 16:49:31 electrum1 electrumxqtum_server[1531599]:   File "/usr/local/lib/python3.9/dist-packages/electrumxqtum/server/session.py", line 1133, in _notify_inner
Jun 07 16:49:31 electrum1 electrumxqtum_server[1531599]:     if eventlog_touched:
Jun 07 16:49:31 electrum1 electrumxqtum_server[1531599]: NameError: name 'eventlog_touched' is not defined
```

**Comment by icodeface** [comment]
unable to reproduce
